# Generated by Django 5.0.3 on 2024-04-02 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_users_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email',
            new_name='name',
        ),
    ]
